#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int divider = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int icons = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int primary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int primary_dark = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int primary_light = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int primary_text = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int secondary_text = 2130771975;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int deviceArt = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int hamburguer_icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int logo = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int phone = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int splash_screen = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int AppCompatDialogStyle = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int AppCompatTheme_Base = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int MyTheme = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int MyThemeAppCompat = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int MyTheme_ActionBarStyle = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int MyTheme_ActionBar_TitleTextStyle = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int Theme_Splash = 2131034118;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
